[build]
builder = "NIXPACKS"
buildCommand = "npm install --legacy-peer-deps"

[deploy]
startCommand = "node voltah.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NIXPACKS_NODE_VERSION = "20"
