services:
  - type: web
    name: june-x-session
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: node voltah.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
